In [28]:
import numpy
import tensorflow as tf
import h5py
import tensorflow.keras
from tensorflow.keras.preprocessing.image import *
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

In [51]:
def preproc(image):
    return image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))

In [54]:
model = VGG16(include_top=False)
model.compile(loss = "categorical_crossentropy",optimizer = tensorflow.keras.optimizers.SGD(lr=0.0001, momentum=0.9))
for layer in model.layers:
   layer.trainable = False
dataGenerator = ImageDataGenerator(preprocessing_function=preproc)
trainingdata = dataGenerator.flow_from_directory(class_mode = None,directory="M:\Year4\Dataset-20191113T110123Z-001\Dataset",target_size=(224,224))
testdata = dataGenerator.flow_from_directory(class_mode = None,directory="M:\Year4\Dataset-20191113T110123Z-001\Dataset",target_size=(224,224))

Found 3430 images belonging to 2 classes.
Found 3430 images belonging to 2 classes.


In [55]:
checkpoint = ModelCheckpoint("vgg16_1.h5", monitor='val_acc', verbose=1, save_best_only=True, save_weights_only=False, mode='auto', period=1)
early = EarlyStopping(monitor='val_acc', min_delta=0, patience=20, verbose=1, mode='auto')
model.fit_generator(steps_per_epoch=100,generator=trainingdata, validation_data= testdata, validation_steps=10,epochs=100,callbacks=[checkpoint,early])

Epoch 1/100


ValueError: Output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: [[[[251. 106. 111.]
   [255. 113. 116.]
   [255. 110. 113.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[252. 112. 115.]
   [255. 119. 123.]
   [250. 105. 108.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[252. 117. 121.]
   [250. 114. 116.]
   [252. 112. 113.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  ...

  [[255. 129. 150.]
   [247. 142. 149.]
   [243. 134. 137.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[236. 171. 177.]
   [255. 225. 230.]
   [255. 153. 164.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[255. 251. 244.]
   [255. 210. 213.]
   [242. 139. 156.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]]


 [[[228. 225. 146.]
   [227. 224. 145.]
   [226. 223. 144.]
   ...
   [ 83.  83.  85.]
   [ 83.  83.  85.]
   [ 83.  83.  85.]]

  [[232. 229. 150.]
   [231. 228. 149.]
   [231. 228. 149.]
   ...
   [ 83.  83.  85.]
   [ 83.  83.  85.]
   [ 83.  83.  85.]]

  [[234. 231. 154.]
   [234. 231. 154.]
   [233. 230. 153.]
   ...
   [ 83.  83.  85.]
   [ 83.  83.  85.]
   [ 83.  83.  85.]]

  ...

  [[ 97. 105. 107.]
   [ 99. 107. 109.]
   [102. 107. 110.]
   ...
   [ 83.  83.  83.]
   [ 83.  83.  83.]
   [ 83.  83.  83.]]

  [[100. 105. 108.]
   [101. 106. 109.]
   [102. 107. 110.]
   ...
   [ 83.  83.  83.]
   [ 83.  83.  83.]
   [ 83.  83.  83.]]

  [[102. 107. 110.]
   [102. 107. 110.]
   [102. 107. 110.]
   ...
   [ 83.  83.  83.]
   [ 83.  83.  83.]
   [ 83.  83.  83.]]]


 [[[223. 223. 235.]
   [223. 223. 235.]
   [223. 223. 235.]
   ...
   [190. 190. 200.]
   [188. 188. 198.]
   [185. 185. 195.]]

  [[223. 223. 235.]
   [223. 223. 235.]
   [223. 223. 235.]
   ...
   [190. 190. 200.]
   [189. 189. 199.]
   [186. 186. 196.]]

  [[223. 223. 235.]
   [223. 223. 235.]
   [223. 223. 235.]
   ...
   [191. 191. 201.]
   [190. 190. 200.]
   [187. 187. 197.]]

  ...

  [[201. 203. 216.]
   [201. 203. 216.]
   [200. 202. 215.]
   ...
   [155. 155. 167.]
   [154. 154. 166.]
   [153. 153. 165.]]

  [[201. 203. 216.]
   [201. 203. 216.]
   [200. 202. 215.]
   ...
   [155. 155. 167.]
   [154. 154. 166.]
   [153. 153. 165.]]

  [[201. 203. 216.]
   [201. 203. 216.]
   [200. 202. 215.]
   ...
   [155. 155. 167.]
   [154. 154. 166.]
   [153. 153. 165.]]]


 ...


 [[[241. 221. 196.]
   [241. 221. 196.]
   [241. 221. 196.]
   ...
   [246. 226. 199.]
   [247. 227. 200.]
   [248. 228. 201.]]

  [[241. 221. 196.]
   [241. 221. 196.]
   [241. 221. 196.]
   ...
   [246. 226. 199.]
   [247. 227. 200.]
   [248. 228. 201.]]

  [[241. 221. 196.]
   [241. 221. 196.]
   [241. 221. 196.]
   ...
   [246. 226. 199.]
   [247. 227. 200.]
   [248. 228. 201.]]

  ...

  [[236. 218. 198.]
   [236. 218. 198.]
   [236. 218. 198.]
   ...
   [188. 168. 141.]
   [191. 171. 144.]
   [193. 173. 146.]]

  [[237. 218. 201.]
   [237. 218. 201.]
   [237. 218. 201.]
   ...
   [188. 168. 141.]
   [191. 171. 144.]
   [193. 173. 146.]]

  [[237. 218. 201.]
   [237. 218. 201.]
   [237. 218. 201.]
   ...
   [188. 168. 141.]
   [191. 171. 144.]
   [193. 173. 146.]]]


 [[[176. 141.  99.]
   [176. 141.  99.]
   [176. 141.  99.]
   ...
   [149. 124.  93.]
   [149. 124.  93.]
   [149. 124.  93.]]

  [[176. 141.  99.]
   [176. 141.  99.]
   [176. 141.  99.]
   ...
   [149. 124.  94.]
   [149. 124.  94.]
   [149. 124.  94.]]

  [[177. 142. 100.]
   [177. 142. 100.]
   [177. 142. 100.]
   ...
   [150. 125.  95.]
   [150. 125.  95.]
   [150. 125.  95.]]

  ...

  [[241. 221. 194.]
   [241. 221. 194.]
   [241. 221. 194.]
   ...
   [183. 173. 163.]
   [179. 169. 159.]
   [177. 167. 158.]]

  [[242. 222. 195.]
   [242. 222. 195.]
   [242. 222. 195.]
   ...
   [182. 172. 162.]
   [179. 169. 159.]
   [176. 166. 157.]]

  [[242. 222. 195.]
   [242. 222. 195.]
   [242. 222. 195.]
   ...
   [181. 171. 161.]
   [178. 168. 158.]
   [175. 165. 156.]]]


 [[[ 84. 240. 226.]
   [ 81. 228. 212.]
   [ 82. 213. 195.]
   ...
   [ 69. 132. 121.]
   [ 61. 129. 118.]
   [ 46. 124. 110.]]

  [[ 80. 238. 224.]
   [ 79. 227. 213.]
   [ 77. 214. 198.]
   ...
   [ 68. 128. 126.]
   [ 84. 155. 151.]
   [ 90. 173. 165.]]

  [[ 80. 240. 228.]
   [ 82. 234. 221.]
   [ 74. 219. 204.]
   ...
   [ 84. 170. 167.]
   [ 90. 197. 189.]
   [ 81. 209. 196.]]

  ...

  [[ 70. 163. 144.]
   [ 76. 152. 140.]
   [ 69. 140. 132.]
   ...
   [101. 102.  97.]
   [ 98.  99.  94.]
   [104. 105. 100.]]

  [[ 62. 155. 134.]
   [ 71. 143. 129.]
   [ 73. 134. 126.]
   ...
   [100. 101.  96.]
   [ 99. 100.  95.]
   [109. 108. 104.]]

  [[ 74. 168. 142.]
   [ 75. 146. 130.]
   [ 72. 129. 120.]
   ...
   [ 97.  98.  93.]
   [103. 102.  98.]
   [111. 110. 106.]]]]